apiVersion: v1
kind: Service
metadata:
  name: tekton-operator-proxy-webhook
  labels:
    version: "devel"
    operator.tekton.dev/release: "devel"
spec:
  ports:
    - name: https-webhook
      port: 443
      targetPort: 8443
  selector:
    name: tekton-operator
