apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-operators-proxy-webhook-admin
subjects:
  - kind: ServiceAccount
    name: tekton-operators-proxy-webhook
    namespace: tekton-operator
roleRef:
  kind: Role
  name: tekton-operators-proxy-admin
  apiGroup: rbac.authorization.k8s.io
