kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tekton-operators-proxy-admin
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "create", "update", "delete", "patch", "watch"]
