apiVersion: apps/v1
kind: Deployment
metadata:
  name: tekton-operator-proxy-webhook
spec:
  template:
    spec:
      containers:
        - name: proxy
          securityContext:
            runAsUser: 65532
